//= require '../shared/lib/shims'
//= require '../shared/constants'

//= require '../shared/lib/helpers'
//= require '../shared/lib/scene_manager'
//= require '../shared/lib/scene'
//= require '../shared/lib/loader'
//= require '../shared/lib/input'
//= require '../shared/lib/sprite'
//= require '../shared/lib/button'
//= require '../shared/lib/gamepad'

//= require '../shared/globals'
//= require 'stretchy_sprite'
//= require '../shared/message'
//= require '../shared/foamenemy'
//= require '../shared/enemy'
//= require '../shared/player'
//= require '../shared/world'

//= require 'scenes/loading_scene'
//= require 'scenes/nick_vs_bus'
//= require '../shared/input_snapshot'

//= require 'main'